### ISSUE TITLE
PWRMON_IO_xxx missing?

### ISSUE THREAD

**Issue by Laxen** [STMicroelectronics/ina230#1]
Hello! I might be missing something here, but it seems like the PWRMON_IO_xxx functions are missing from this repo? The functions are defined in the header file but not in the C file and I can't find them in any of the other BSP files. Is there anything else I need to build this?

(I'm using the [BSP drivers for STM32L451RE](https://github.com/STMicroelectronics/STM32CubeL4) if that matters)

Thanks!

**Comment by RKOUSTM** [comment]
Hi @Laxen,

Thank you for your report. Indeed, the INA230 BSP component is not supported by any STM32L4 board but it is supported by the STM32G071B-Discovery board. In fact, the following **PWRMON IO functions** 
https://github.com/STMicroelectronics/stm32-ina230/blob/45f9ccfccbb4806923c2b6cded6e2b3649649163/ina230.h#L325-L332
are defined in [this](https://github.com/STMicroelectronics/stm32g071b-disco/blob/main/stm32g071b_discovery.c) stm32g071b_discovery.c file. In order to correctly compile your application, you need to include the necessary files of the BSP board used.

Feel free to reach out if you have additional questions. 
Thank you again for your report. We are looking forward to reading from you again.

With regards,
